replicaCount: 2

image:
  repository: nginxdemos/hello
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

deployment:
  api_version: apps/v1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: hello-world.info
      paths:
        - path: /
          pathType: Prefix

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
